
// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.9.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'output_directory': '/home/dokken/Documents/src/FEniCS-workshop/src',
//   'profile': False,
//   'scalar_type': 'float64',
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'ufl_file': ['/home/dokken/Documents/src/FEniCS-workshop/src/ufl_formulation.py'],
//   'verbosity': 30,
//   'visualise': True}

#pragma once
#include <ufcx.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufcx_integral integral_72453e6970f39670be718c17ab8a2eefd72b5b6e;

extern ufcx_integral integral_5f3a0a020d959b598d839e3e41ad0d7402e3607a;

extern ufcx_form form_60bd7d1b5b09ecd5835279d08c73daa087ee5aea;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_a;


extern ufcx_form form_c7c80fcfd945d845b9e2823cc09d2748fa65215b;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufcx_form* form_ufl_formulation_L;


#ifdef __cplusplus
}
#endif
